sudo: false
language: rust
rust:
- 1.22.0 # oldest supported version
- stable
- beta
- nightly

matrix:
  include:
  - rust: 1.24.0  # `stable`: Locking down for consistent behavior
    env: RUSTFMT
    install:
    - rustup component add rustfmt-preview
    script:
    - cargo fmt -- --write-mode=diff

install:
- rustc -Vv
- cargo -V

script:
- cargo check --verbose
- cargo test --verbose
- cargo doc --no-deps

cache:
  cargo: true
