sudo: false
language: rust
rust:
- 1.22.0 # oldest supported version
- stable
- beta
- nightly

matrix:
  include:
  - env: RUSTFMT
    rust: 1.24.0  # `stable`: Locking down for consistent behavior
    install:
    - rustup component add rustfmt-preview
    script:
    - cargo fmt -- --write-mode=diff
  - env: RUSTFLAGS="-D warnings"
    rust: 1.24.0  # `stable`: Locking down for consistent behavior
    script:
    - cargo check --tests
  - env: CLIPPY_VERSION=0.0.179
    rust: nightly-2018-01-12
    install:
    - travis_wait cargo install clippy --version $CLIPPY_VERSION || echo "clippy already installed"
    script:
    - cargo clippy -- -D clippy

install:
- rustc -Vv
- cargo -V

script:
- cargo check --verbose
- cargo test --verbose
- cargo doc --no-deps

cache:
  cargo: true
